# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    input_sync: true
    base_path: "build/ckeditor"
    js_path: "build/ckeditor/ckeditor.js"
    jquery_path: "build/ckeditor/adapters/jquery.js"
    default_config: tools_config
    configs:
        tools_config:
            toolbar: standard