vich_uploader:
    db_driver: orm

    mappings:
        project_images:
            uri_prefix: '%app.path.project_images%'
            upload_destination: '%kernel.project_dir%/public/%app.path.project_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false

        attachments:
            uri_prefix: '%app.path.attchments_image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.attchments_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false

        teams_image:
            uri_prefix: '%app.path.teams_image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.teams_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false